//
//  GoldenCorpusTests.swift
//  ATCReplayKitTests
//
//  The compatibility contract: recordings written by an earlier build, committed as bytes.
//
//  ── Why this is not redundant with the other 170 tests ─────────────────────
//  Every existing coding test writes with `EventCoder` and reads with `EventCoder`. That proves the pair agrees
//  with itself, which is not the property that matters. A *symmetric* change — renaming a JSON key, reordering a
//  frame header, altering how an optional is spelled — keeps both sides agreeing and silently makes every stored
//  recording unreadable. The suite stays green while the archive is destroyed.
//
//  These fixtures break the symmetry. They were produced once, committed, and are never regenerated by a normal
//  run. From here on, a change that alters the on-disk format fails loudly, and the failure names the byte.
//
//  ── What is frozen ─────────────────────────────────────────────────────────
//  · the manifest's encoded bytes
//  · every event's encoded bytes, one per line, base64
//  · the framed log — magic, length prefix, crc32, in order
//  · the seal over manifest + log
//
//  All four matter for different reasons. The event bytes are what a reader parses; the frame bytes are what the
//  log walker steps through; the seal is what makes an assessment evidence. A change could break any one of them
//  without touching the others.
//
//  ── Regenerating ───────────────────────────────────────────────────────────
//  `REGENERATE_GOLDEN_CORPUS=1 swift test --filter GoldenCorpus`
//
//  Only ever legitimate when the format is *intentionally* revised, and then only together with a read-time
//  migration and a second corpus kept alongside this one — never by replacing it. A corpus that gets regenerated
//  whenever it fails is a corpus that proves nothing.
//

import XCTest
@testable import ATCReplayKit

final class GoldenCorpusTests: XCTestCase {

    // MARK: - The corpus

    /// Fixed so the bytes are fixed. A derived `EventID` is `(sessionID, ordinal)`, so freezing the session id
    /// freezes every id in the corpus too.
    private static let sessionID = UUID(uuidString: "5A11A5E5-0000-4000-8000-000000000001")!

    private static let createdAt = Date(timeIntervalSince1970: 1_770_000_000)

    /// Deliberately not `.current()`: the corpus must not change when the build or the machine does.
    private static let environment = RecordingEnvironment(buildVersion: "1.0.0-corpus",
                                                          architecture: "arm64",
                                                          platform: "corpus")

    private static let manifest = SessionManifest(
        sessionID: sessionID,
        origin: .selfDirected,
        seed: 0x5A11_A5E5,
        ownerID: .user("corpus-owner"),
        environment: environment,
        exercise: EmbeddedExercise(payload: Data("{\"exerciseName\":\"Corpus\"}".utf8),
                                   exerciseID: "corpus-1",
                                   exerciseName: "Corpus"),
        createdAt: createdAt)

    /// One event of **every** `EventKind`, plus the envelope features that are easy to break: a non-default
    /// source, a correlation, a causation, and an audit-only wall clock.
    ///
    /// All seven kinds on purpose. Phase R2 moves this vocabulary into an adapter and makes the payload opaque to
    /// the core; the tags 1…7 and their encodings must survive that move exactly, and a corpus missing a kind is
    /// a kind nobody notices breaking.
    private static var corpus: [Event] {
        let root = EventID(session: sessionID, ordinal: 0)
        return [
            Event(position: EventPosition(tick: 0, ordinal: 0),
                  payload: .timelineAction(.replayStarted),
                  source: .system),

            Event(position: EventPosition(tick: 12, ordinal: 1),
                  payload: .transcriptReceived(raw: "AIC two three one descend flight level two six zero",
                                               normalized: "AIC231 DESCEND FL260"),
                  source: .voice,
                  wallClock: Date(timeIntervalSince1970: 1_770_000_012)),

            Event(position: EventPosition(tick: 12, ordinal: 2),
                  payload: .commandIssued(code: "C/M*", callsign: "AIC231",
                                          slots: ["level": "260", "unit": "FL"]),
                  source: .voice,
                  correlationID: root,
                  causationID: root),

            Event(position: EventPosition(tick: 12, ordinal: 3),
                  payload: .readbackSpoken(callsign: "AIC231", spoken: "descending flight level two six zero"),
                  source: .system,
                  correlationID: root),

            Event(position: EventPosition(tick: 30, ordinal: 4),
                  payload: .commandRejected(code: "H/M*", callsign: nil,
                                            reason: "no aircraft selected"),
                  source: .keypad),

            Event(position: EventPosition(tick: 60, ordinal: 5),
                  payload: .weatherChanged(windDegrees: 270, windKnots: 12,
                                           visibilityMetres: 8_000, qnh: 1013),
                  source: .instructor),

            // Nil-heavy on purpose: an absent optional must stay absent rather than becoming null, which is a
            // distinction a reader would otherwise have to spell two ways.
            Event(position: EventPosition(tick: 90, ordinal: 6),
                  payload: .weatherChanged(windDegrees: nil, windKnots: nil,
                                           visibilityMetres: nil, qnh: nil),
                  source: .automation),

            Event(position: EventPosition(tick: 120, ordinal: 7),
                  payload: .scoreEvaluated(value: 87, rulesVersion: "atc-scoring-1.2.0"),
                  source: .system),

            Event(position: EventPosition(tick: 150, ordinal: 8),
                  payload: .timelineAction(.speedChanged(to: 4)),
                  source: .replay),
        ]
    }

    // MARK: - Fixture locations

    /// Beside the source rather than as a SwiftPM resource, because regeneration has to write back into the
    /// repository and a bundled resource is read-only at test time.
    private static var fixtures: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/GoldenCorpus", isDirectory: true)
    }

    private static var isRegenerating: Bool {
        ProcessInfo.processInfo.environment["REGENERATE_GOLDEN_CORPUS"] == "1"
    }

    private func fixture(_ name: String) -> URL {
        Self.fixtures.appendingPathComponent(name)
    }

    // MARK: - Building the current bytes

    /// The framed log exactly as `EventStore` writes it, plus each frame on its own.
    private func currentLog() throws -> (log: Data, frames: [Data]) {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("corpus-\(UUID().uuidString).log")
        defer { try? FileManager.default.removeItem(at: url) }

        let store = EventStore(url: url, sessionClass: .training)
        try store.openForAppending()
        var frames: [Data] = []
        for event in Self.corpus {
            frames.append(try store.append(event))
        }
        try store.flush()
        try store.close()

        return (try Data(contentsOf: url), frames)
    }

    // MARK: - 1 · The contract

    /// **The compatibility contract.** Committed bytes must still decode, and re-encoding must reproduce them.
    ///
    /// Both directions, because they fail differently: a decode failure means old recordings cannot be read, and
    /// an encode difference means new recordings are written in a dialect the old reader does not know. Only the
    /// pair rules out both.
    func testTheCommittedCorpusStillRoundTripsByteForByte() throws {
        let coder = EventCoder()

        if Self.isRegenerating {
            try regenerate(coder: coder)
            // Deliberately not "XCTFail so nobody commits by accident": the whole point of the flag is that
            // regenerating is an explicit, reviewed act. The commit diff is the review.
            print("[corpus] regenerated at \(Self.fixtures.path)")
            return
        }

        // ── Manifest ──────────────────────────────────────────────────────────
        let manifestBytes = try Data(contentsOf: fixture("manifest.json"))
        let decodedManifest = try SessionManifest.decode(manifestBytes)
        XCTAssertEqual(decodedManifest, Self.manifest,
                       "a stored manifest no longer decodes to the same value")
        XCTAssertEqual(try decodedManifest.encoded(), manifestBytes,
                       "re-encoding a stored manifest changed its bytes — the seal over it would move")

        // ── Events, one line at a time ────────────────────────────────────────
        let lines = try String(contentsOf: fixture("events.b64"), encoding: .utf8)
            .split(separator: "\n").map(String.init)
        XCTAssertEqual(lines.count, Self.corpus.count,
                       "the corpus changed size — add a new fixture rather than editing this one")

        for (index, line) in lines.enumerated() {
            let stored = try XCTUnwrap(Data(base64Encoded: line), "fixture line \(index) is not base64")

            // Envelope first, and without the payload: this is the property that lets an index be built over
            // events a build cannot decode, so it has to hold on its own.
            let envelope = try coder.decodeEnvelope(stored)
            XCTAssertEqual(envelope.position, Self.corpus[index].position,
                           "event \(index): position moved")
            XCTAssertEqual(envelope.source, Self.corpus[index].source,
                           "event \(index): source moved")
            XCTAssertEqual(envelope.eventType, Self.corpus[index].payload.kind,
                           "event \(index): wire tag changed — stored recordings now mean something else")

            let event = try coder.decode(stored)
            XCTAssertEqual(event, Self.corpus[index], "event \(index): decoded to a different value")
            XCTAssertEqual(try coder.encode(event), stored,
                           "event \(index): re-encoding changed the bytes")
        }

        // ── The framed log ────────────────────────────────────────────────────
        let storedLog = try Data(contentsOf: fixture("events.log"))
        let (currentBytes, _) = try currentLog()
        XCTAssertEqual(currentBytes, storedLog,
                       "the frame format changed — magic, length prefix, crc32 or ordering")

        // Reading it back through the store, so the walker is exercised and not just the writer.
        let readURL = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("corpus-read-\(UUID().uuidString).log")
        try storedLog.write(to: readURL)
        defer { try? FileManager.default.removeItem(at: readURL) }
        let reread = try EventStore(url: readURL, sessionClass: .training).readAll()
        XCTAssertEqual(reread, Self.corpus, "a stored log no longer reads back as the events that made it")

        // ── The seal ──────────────────────────────────────────────────────────
        let storedSeal = try String(contentsOf: fixture("seal.txt"), encoding: .utf8)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        XCTAssertEqual(SessionSeal.compute(manifest: manifestBytes, log: storedLog), storedSeal,
                       "the seal over an unchanged session changed — every stored assessment would fail to verify")
    }

    /// The incremental seal must agree with the one-pass seal **on the corpus**, not only on synthetic frames.
    ///
    /// `SessionSealTests` already asserts the two forms agree; this asserts they agree on the exact bytes an
    /// assessment is verified against, which is the case that actually has to hold.
    func testBothSealFormsAgreeOnTheCorpus() throws {
        try XCTSkipIf(Self.isRegenerating, "regenerating")

        let manifestBytes = try Data(contentsOf: fixture("manifest.json"))
        let storedLog = try Data(contentsOf: fixture("events.log"))
        let (_, frames) = try currentLog()

        var builder = SessionSealBuilder(manifest: manifestBytes)
        for frame in frames { builder.add(frame: frame) }

        XCTAssertEqual(builder.seal(), SessionSeal.compute(manifest: manifestBytes, log: storedLog))
        XCTAssertEqual(builder.frameCount, Self.corpus.count)
    }

    /// Every `EventKind` appears in the corpus.
    ///
    /// Guards the corpus rather than the code: a kind added later without a fixture is a kind whose encoding
    /// nothing freezes, and it would go unnoticed precisely because all the other tests pass.
    func testTheCorpusCoversEveryEventKind() {
        let covered = Set(Self.corpus.map(\.payload.kind))
        XCTAssertEqual(covered, Set(EventKind.allCases),
                       "add a corpus event for every new EventKind, and regenerate deliberately")
    }

    /// `affectsSimulation` frozen **by wire tag**.
    ///
    /// Phase R2 moves this decision out of the payload enum and onto a tag table in the ATC codec. That is the
    /// single most dangerous edit in the extraction: get it wrong and a replay silently skips a real input or
    /// applies an annotation. This table is what the new implementation will be checked against.
    func testWhichKindsAffectTheSimulationIsFrozen() {
        let expected: [EventKind: Bool] = [
            .commandIssued: true,
            .weatherChanged: true,
            .commandRejected: false,
            .transcriptReceived: false,
            .readbackSpoken: false,
            .scoreEvaluated: false,
            .timelineAction: false,
        ]

        for event in Self.corpus {
            let kind = event.payload.kind
            XCTAssertEqual(event.payload.affectsSimulation, expected[kind],
                           "\(kind) changed whether it feeds the simulation — replay would diverge")
        }
        XCTAssertEqual(Set(expected.keys), Set(EventKind.allCases),
                       "a new kind must declare whether it affects the simulation")
    }

    // MARK: - Regeneration

    private func regenerate(coder: EventCoder) throws {
        try FileManager.default.createDirectory(at: Self.fixtures, withIntermediateDirectories: true)

        try Self.manifest.encoded().write(to: fixture("manifest.json"))

        let lines = try Self.corpus.map { try coder.encode($0).base64EncodedString() }
        try lines.joined(separator: "\n").write(to: fixture("events.b64"),
                                               atomically: true, encoding: String.Encoding.utf8)

        let (log, _) = try currentLog()
        try log.write(to: fixture("events.log"))

        let seal = SessionSeal.compute(manifest: try Self.manifest.encoded(), log: log)
        try seal.write(to: fixture("seal.txt"), atomically: true, encoding: String.Encoding.utf8)
    }
}
