//
//  DeterminismSelfCheck.swift
//  ATCSimKit
//
//  Answers one question: does this device compute the simulation the same way the recording did?
//
//  ── Why this ships, rather than living in a test ────────────────────────────
//  Replay works by re-running the simulation, so a recording is only faithful on a machine that
//  computes it identically. Within one architecture that holds: IEEE-754 double arithmetic is
//  bit-reproducible for the same binary. Across architectures it may not — `sin`, `cos` and `atan2`
//  are library functions, not hardware instructions, and their last bits can differ between an
//  arm64 device and an x86_64 simulator. Every aircraft position in this simulator is computed
//  through great-circle maths, so that is exactly the code path at risk.
//
//  That matters beyond correctness. An assessment replayed on a machine that computes differently
//  is not what the trainee flew, so it must be marked unscoreable rather than quietly reviewed. The
//  app cannot know that without asking, and this is the question: run a fixed scenario, compare the
//  fingerprint against the one compiled in.
//
//  So this is a shipping capability, not test scaffolding — though the test suites are its first
//  callers, and they are what makes it meaningful: the same constant is asserted from macOS and
//  from the iOS simulator, which is the cross-platform measurement the architecture called for.
//
//  ── What it deliberately does not do ───────────────────────────────────────
//  It does not step the whole simulation. The scenario is physics and geodesy only — the
//  float-sensitive part — so the check stays stable when spawning, scheduling or command handling
//  change. A self-check that broke every time an unrelated feature landed would be switched off,
//  and a switched-off check is worse than none.
//

import Foundation
import CoreLocation
import GeoNavKit

/// Verifies that this platform computes the simulation's arithmetic as expected.
public enum DeterminismSelfCheck {

    /// What the check found.
    public enum Result: Equatable, Sendable {
        /// This platform matches. A recording made elsewhere can be replayed and scored here.
        case matches
        /// This platform computes differently. Replay is still useful for review, but a result
        /// produced here cannot be compared against one produced elsewhere.
        case diverged(fingerprint: UInt64)

        public var isTrustworthy: Bool { self == .matches }
    }

    /// Runs the fixed scenario and compares it against the compiled-in fingerprint.
    public static func run() -> Result {
        let actual = fingerprint()
        return actual == expectedFingerprint ? .matches : .diverged(fingerprint: actual)
    }

    /// The fingerprint this scenario produces on a platform that agrees.
    ///
    /// Generated by `fingerprint()` and pasted here. **Do not regenerate it to make a failing test
    /// pass** — a mismatch means either that this platform computes differently, which is the thing
    /// being detected, or that the physics changed, which invalidates every existing recording and
    /// is a deliberate decision rather than a test fix.
    public static let expectedFingerprint: UInt64 = 0x95A9_2889_F6E7_9EBC

    // MARK: - The scenario

    /// How many steps the scenario runs.
    ///
    /// Long enough that a last-bit difference has room to grow into something visible: each step
    /// feeds the previous position back through `Geo.offset`, so an error compounds. A handful of
    /// steps could hide a divergence that six hundred will not.
    public static let steps = 600

    /// Steps a small fixed scenario and fingerprints the outcome.
    ///
    /// Public so a failing check can report what this platform actually produced, and so the value
    /// can be regenerated deliberately when the physics genuinely changes.
    public static func fingerprint() -> UInt64 {
        var clock = SimulationClock()
        var aircraft = scenario()
        let physics = AircraftPhysics.shared

        for _ in 0..<steps {
            for index in aircraft.indices {
                physics.stepPhysics(&aircraft[index], dt: SimulationClock.tickInterval)
            }
            clock.advance()
        }
        return StateHash(clock: clock, radar: aircraft, hangar: []).value
    }

    /// Four aircraft, each exercising a different arithmetic path.
    ///
    /// Fixed ids and positions, because the fingerprint has to be reproducible: a random id or a
    /// spawn point would make this check compare nothing.
    private static func scenario() -> [Aircraft] {
        // Turning, climbing, and accelerating at once — the case where turn integration, vertical
        // rate and speed change all compound into the position.
        var turning = make(id: 1, "TURN01", lat: 28.5562, lon: 77.1000, heading: 90)
        turning.targetHeading = 250
        turning.turnDirection = .right
        turning.targetAltitudeFeet = 26_000
        turning.targetSpeedKnots = 320

        // Straight and level: the purest test of `Geo.offset` compounding, with nothing else moving.
        let cruising = make(id: 2, "CRUZ02", lat: 28.7000, lon: 77.3000, heading: 45)

        // Descending through a left turn, so the sign conventions get exercised too.
        var descending = make(id: 3, "DESC03", lat: 28.3000, lon: 76.9000, heading: 180)
        descending.targetHeading = 90
        descending.turnDirection = .left
        descending.targetAltitudeFeet = 8_000
        descending.targetSpeedKnots = 210

        // A heading that crosses north, where the 0/360 wrap is easy to get subtly wrong.
        var wrapping = make(id: 4, "WRAP04", lat: 28.9000, lon: 77.5000, heading: 350)
        wrapping.targetHeading = 20

        return [turning, cruising, descending, wrapping]
    }

    private static func make(id: UInt8,
                             _ callsign: String,
                             lat: Double,
                             lon: Double,
                             heading: Double) -> Aircraft {
        var bytes = [UInt8](repeating: 0, count: 16)
        bytes[15] = id
        return Aircraft(id: UUID(uuid: (bytes[0], bytes[1], bytes[2], bytes[3],
                                        bytes[4], bytes[5], bytes[6], bytes[7],
                                        bytes[8], bytes[9], bytes[10], bytes[11],
                                        bytes[12], bytes[13], bytes[14], bytes[15])),
                        callsign: callsign,
                        position: CLLocationCoordinate2D(latitude: lat, longitude: lon),
                        headingDegrees: heading)
    }
}
