//
//  EventSource.swift
//  ATCReplayKit
//
//  Where a recorded event came from.
//
//  Not used for ordering or for replay — those are `(tick, ordinal)` and the payload. This is for the
//  questions asked *about* a session afterwards: did this trainee rely on the keypad, which instructions
//  did an instructor inject, was this transmission spoken or typed, which events came from another
//  machine.
//
//  ── A struct, not an enum ───────────────────────────────────────────────────
//  An enum would be tidier to read and wrong for a stored format. Decoding an enum requires every value
//  to be known, so a recording written by a newer build — one that had learned about a source this build
//  has not — would fail to decode *entirely*, losing events for a field nobody was even reading.
//
//  So this is the extensible-constant pattern the standard library uses for `Notification.Name`: a
//  `String` wrapper with named constants. Any value decodes; unknown ones survive intact and can still
//  be displayed, filtered and round-tripped. **Adding a source never touches an existing recording, and
//  never stops one being read.**
//
//  The trade is that the compiler cannot check exhaustiveness at a `switch`. That is the right way round
//  here: the set of sources is open by nature — multiplayer will add at least one — and a compile error
//  in a consumer is a cheaper problem than an unreadable recording.
//

import Foundation

/// Where an event originated.
public struct EventSource: RawRepresentable, Hashable, Codable, Sendable, CustomStringConvertible {

    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public var description: String { rawValue }

    // MARK: - Known sources

    /// Spoken by the controller and recognised from a transcript.
    public static let voice = EventSource(rawValue: "voice")

    /// Issued from the command keypad.
    public static let keypad = EventSource(rawValue: "keypad")

    /// A decision the simulator's own traffic logic made — not a human instruction.
    public static let ai = EventSource(rawValue: "ai")

    /// Generated by the app rather than by anyone: a readback spoken, a score evaluated, a session
    /// paused because the app went to the background.
    public static let system = EventSource(rawValue: "system")

    /// Injected by an instructor rather than issued by the trainee under assessment. Worth telling apart
    /// from the trainee's own inputs, since an assessment should not credit or blame them for it.
    public static let instructor = EventSource(rawValue: "instructor")

    /// Fed back in by the replay engine.
    ///
    /// In normal operation replay does **not** record — recording is off while replaying — so this
    /// should not appear in a session log. It exists so that a diagnostic recording *of a replay* is
    /// distinguishable from the original, rather than looking like a second real run.
    public static let replay = EventSource(rawValue: "replay")

    /// Arrived from another machine. Unused until multiplayer; declared now so that when it arrives, no
    /// recording written before it needs changing.
    public static let network = EventSource(rawValue: "network")

    /// Driven by a script or a test rather than by a person.
    public static let automation = EventSource(rawValue: "automation")

    /// The source was not recorded.
    ///
    /// Distinct from every other value on purpose: it means "we do not know", which is different from
    /// any particular answer. Used when reading a recording that predates this field, so an old session
    /// is never made to claim an attribution it never had.
    public static let unspecified = EventSource(rawValue: "unspecified")

    /// Every source this build knows about.
    ///
    /// For a filter UI, and for recognising that a recording named something newer — see `isKnown`.
    public static let allKnown: [EventSource] = [
        .voice, .keypad, .ai, .system, .instructor, .replay, .network, .automation, .unspecified,
    ]

    /// Whether this build recognises the value.
    ///
    /// False for a source written by a newer build. Worth surfacing rather than hiding: "3 events from a
    /// source this version does not know" is useful in a diagnostic, and silently lumping them in with
    /// something familiar would be a lie.
    public var isKnown: Bool { Self.allKnown.contains(self) }

    // MARK: - Grouping

    /// Whether a person did this.
    ///
    /// The distinction analytics actually wants: "how much of this exercise did the trainee drive" is a
    /// different question from "how much did the simulator". Computed from the known set, so an
    /// unrecognised source is neither — which is the honest answer for something we cannot classify.
    public var isHuman: Bool {
        self == .voice || self == .keypad || self == .instructor
    }

    /// Whether the machine did this.
    public var isSynthetic: Bool {
        self == .ai || self == .system || self == .replay || self == .automation
    }

    /// Whether this came from the trainee being assessed, as opposed to an instructor or the simulator.
    ///
    /// The one grouping with a consequence rather than an insight: an assessment must not credit or
    /// blame a trainee for an instruction somebody else injected.
    public var isAttributableToTrainee: Bool {
        self == .voice || self == .keypad
    }
}
